function MenuShow(){
    let MenuShow=document.getElementById("div")
    MenuShow.style.display="flex"
    let SD=document.getElementById("Menu")
    SD.style.display="none"
    let ui=document.getElementById("Closemenu")    
    ui.style.display="block"
}
function MenuClose(){
    let MenuClose=document.getElementById("div")
    MenuClose.style.display="none"
let DS=document.getElementById("Closemenu")
    DS.style.display="none"
    let SD=document.getElementById("Menu")
    SD.style.display="block"

}